### ISSUE TITLE
Running fragment explorer with ProteomeTools files fails 

### ISSUE THREAD

**Issue by louisebuur** [michabirklbauer/internal_ions#46]
I have analysed one file from ProteomeTools (02330a_BA4_4087_1_PTM_TrainKit_Ymod_Phospho_200fmol_3xHCD_R1)
I used ThermoRawfileParser to convert the raw file to mgf and then searched it with MS Amanda and got the mzid output 

I still see the error that you discuss in issue #40, but I also have an error with reading in the mzid. I used the version that is on the server from Veit (with the link from Slack)

The mgf file and mzid files are available [here](https://drive.google.com/drive/folders/14sTihh0SrFM__09xJkDwuxCwkUXNoczI?usp=sharing)

For you @michabirklbauer I think it's easier to get them from our shared bin-prot drive: 
O:\louise\ProteomeTools_data 
02330a_BA4_4087_1_PTM_TrainKit_Ymod_Phospho_200fmol_3xHCD_R1.mgf
02330a_BA4_4087_1_PTM_TrainKit_Ymod_Phospho_200fmol_3xHCD_R1_output_2.mzid
 
![image](https://github.com/michabirklbauer/internal_ions/assets/77845950/39159b17-98d0-4476-88c1-6b271d0e8cf9)
![image](https://github.com/michabirklbauer/internal_ions/assets/77845950/d312b4c3-adec-4921-af06-352a63f72c60)

**Comment by michabirklbauer** [comment]
I can't reproduce this error unfortunately, it runs fine for me 😅

**Comment by michabirklbauer** [comment]
Also ran fine on the server now. Maybe the server just had a bad day when you tried it ;)

**Comment by louisebuur** [comment]
I tried it today with the version on the server that Veit sent to us the other day and it works 😃

**Comment by michabirklbauer** [comment]
Wuhuu 💯
