### ISSUE TITLE
Filtering options for spectrum-centric and fragment-centric views

### ISSUE THREAD

**Issue by veitveit** [michabirklbauer/internal_ions#49]
Add options to each column for filtering for
- value range when numeric
- names when many characters like sequences
- values when list of names (e.g. fragment type)

This is rather easily doable in R shiny:
see section 2.8 in https://rstudio.github.io/DT/
Maybe https://staggrid-examples.streamlit.app/ ? Seems to be quite similar.

__Open points to solve__:
- Update fragment-centric table when making selection in spectrum-centric table?
- How to select? Via button (e.g. all filtered rows)?
- When do update figures?

**Comment by michabirklbauer** [comment]
https://blog.streamlit.io/auto-generate-a-dataframe-filtering-ui-in-streamlit-with-filter_dataframe/

**Comment by veitveit** [comment]
Also an option but seems to be more complicated to implement than this staggrid one.

**Comment by michabirklbauer** [comment]
> Also an option but seems to be more complicated to implement than this staggrid one.

Yes for sure! Sorry, just meant to post it for myself to keep it in mind in case something doesn't work out 😄
