### ISSUE TITLE
Error for large fragment-centric table

### ISSUE THREAD

**Issue by veitveit** [michabirklbauer/internal_ions#51]
![image](https://github.com/michabirklbauer/internal_ions/assets/15800709/da0313f9-524b-4fd2-b815-84b8a94eb2e0)

The further visualizations still seem to work though

**Comment by michabirklbauer** [comment]
I can set the size limit to 1GB, but as the warning says - it might slow down the whole thing displaying the whole dataframe. It's also going to be interesting how responsive the filtering is going to be with dataframes of this size 😄

**Comment by veitveit** [comment]
This was not much of an issue when running the app on the server but I agree that this will be a problem on a normal computer. 

And I just checked: Many many fragment ions are the non-annotated ones, leading to the bloating of the dataframe.
The csv-file has >500MB with 6M rows, out of which 4.7M start with "n:n@0:0(+0)"

So there is for sure quite some redundancy.

**Comment by michabirklbauer** [comment]
We could just only display the annotated stuff, I don't think there's much to get out of for the user seeing 4.7M non-annotated peaks. Especially since the information should be coming from the visualizations anyway
